name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    -name: checkout
      uses: actions/checkout@v2
      #working-directory: 
    
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1
  
    - name: msbuild
      run: msbuild
    
