name: CI

on: 
  push:
  schedule:
    - cron: '1 1 * * 1,4'

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
    
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Cache vcpkg modules
        uses: actions/cache@v1
        with:
          path: /vcpkg 
          key: cache 
      
      - name: Build Microsofts rest library
        run: vcpkg install cpprestsdk cpprestsdk:x64-windows
        
      - name: Integrate vcpkg files
        run: vcpkg integrate install

      - name: msbuild
        run: msbuild -property:Configuration=Release -property:ProcessorArchitecture=x64
    
